server:
  port: 8083

spring:
  application:
    name: admin-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/mystore_admin?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ajjuvarsh@7
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.mystore.admin: DEBUG
    org.springframework.security: DEBUG

# JWT Configuration
jwt:
  secret: mySecretKey
  expiration: 86400000 # 24 hours